configured_endpoints: 2
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/carbontrail-limited%2Fcarbonapi-51a5a45a7e4ec3a5e9814a6e7c020d2493a2bfcca903c0021e7a974255bdf1c6.yml
