configured_endpoints: 2
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/carbontrail-limited%2Fcarbonapi-b9474fc194bed01b688818e0dd35ac56526eb3f71b5fcd9ecb0cc882b46c0ad9.yml
