configured_endpoints: 2
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/carbontrail-limited%2Fcarbonapi-d4eb9c9f88fef243f7e5f7c9e2dccdb4d0f091acad7bae751c29f71c33a8fa63.yml
