configured_endpoints: 2
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/carbontrail-limited%2Fcarbonapi-e5a634e8e7217504e3db17a63f53778fd024e0d14b37250f863f53cfd10f5e2e.yml
